title: "Milin Doppalapudi"
description: "Machine Learning Engineer | Computer Vision"
url: "https://midoppal.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme

minimal_mistakes_skin: "air"

include:
  - _pages
