title: "Milin Doppalapudi" 
description: "Machine Learning Engineer | Computer Vision" 
url: "https://midoppal.github.io" 
baseurl: "" 
markdown: kramdown 
# theme: minima 
remote_theme: "daattali/beautiful-jekyll"

plugins: 
  - jekyll-remote-theme 

header_pages: 
  - projects.md 
  - papers.md
